# Generated by Django 4.1.7 on 2023-05-11 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MGIH', '0002_alter_ingredient_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredient',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
