# Generated by Django 4.1.7 on 2023-05-15 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MGIH', '0003_alter_ingredient_timestamp'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='cook_time',
            field=models.CharField(default=0, max_length=32),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='recipe',
            name='prep_time',
            field=models.CharField(default=0, max_length=32),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='recipe',
            name='servings',
            field=models.CharField(default=0, max_length=32),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='recipe',
            name='total_time',
            field=models.CharField(default=0, max_length=32),
            preserve_default=False,
        ),
    ]
