# Generated by Django 4.1.7 on 2023-05-16 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MGIH', '0004_recipe_cook_time_recipe_prep_time_recipe_servings_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipeingredient',
            name='measurement_quantity',
        ),
        migrations.RemoveField(
            model_name='recipeingredient',
            name='measurement_type',
        ),
        migrations.AddField(
            model_name='recipeingredient',
            name='measurement',
            field=models.CharField(default=0, max_length=64),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Measurement',
        ),
    ]
