# Generated by Django 4.1.7 on 2023-05-16 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MGIH', '0005_remove_recipeingredient_measurement_quantity_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='image',
            field=models.ImageField(blank=True, upload_to='static/MGIH/'),
        ),
    ]
