# Generated by Django 4.1.7 on 2023-05-26 19:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MGIH', '0006_recipe_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='save',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_recipes', to=settings.AUTH_USER_MODEL),
        ),
    ]
