# Generated by Django 4.1.7 on 2023-03-21 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0002_auction_listings_comments_bids_user_watchlist'),
    ]

    operations = [
        migrations.AddField(
            model_name='auction_listings',
            name='open',
            field=models.BooleanField(default=True),
        ),
    ]
