# Generated by Django 4.1.7 on 2023-03-23 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0003_auction_listings_open'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auction_listings',
            name='image',
            field=models.ImageField(blank=True, upload_to='static/auctions/'),
        ),
    ]
